### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by ian-nevda** [arusanov/avatar-generator#19]
Hi,

Thank you for posting this generator. I am not very knowledgeable with javascript and would appreciate any help. Trying to implement the avatar generator into my simple CRUD blog app.

Here is my post route, however, it doesn't work and returns an error that await can only be used in an async function. I tried using the generator in different ways but so far have not been able to make it work.

```
router.post("/register", function(req, res) {
        const avatar = new AvatarGenerator({
        parts: ['background', 'face', 'clothes', 'head', 'hair', 'eye', 'mouth'], //order in which sprites should be combined
        partsLocation: path.join(__dirname, '../node_modules/avatar-generator/img'), // path to sprites
        imageExtension: '.png' // sprite file extension
    });

    const variant = 'male';

    const image = await avatar.generate(req.body.email, variant).toFile('output.png');

    var newUser = new User({ username: req.body.username, email: req.body.email, avatar: image });
```

**Comment by dandarie** [comment]
To use await, the above code should run in a function declared with async. Otherwise, remove the await and use .then().

But this is besides the scope of this library.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
