### ISSUE TITLE
receiving error "variant 'female' is not supported. Supported variants:"

### ISSUE THREAD

**Issue by simabui** [arusanov/avatar-generator#21]
what type of variants does it support?
Because 'male' and 'female' doesn't support

```
const avatar = new AvatarGenerator({
  partsLocation: path.join(__dirname, '../../tmp'),
  imageExtension: '.jpg', // sprite file extension
});


const image = await avatar.generate(newUser.email, 'female');
 image.jpg().toFile('test.jpg');
```
**ERROR**
variant 'female' is not supported. Supported variants:

**Comment by arusanov** [comment]
what's in `'../../tmp'` directory?

**Comment by simabui** [comment]
empty folder where I suppose to save generated avatars

**Comment by arusanov** [comment]
it's supposed to be source folder. you don't need to pass it, unless you
want to override sprites from which avatars are generated
