### ISSUE TITLE
How to use on a web server?

### ISSUE THREAD

**Issue by srednas** [arusanov/avatar-generator#3]
This is not an issue, but rather a question on the usage.

How do you use this code on a webserver? I need to be able to return a base64 encoded string (like your demo site does) to use in my site. How can I do that?

**Comment by arusanov** [comment]
Hi. You can use it like this:
```
avatar('User ID (email or hash or any string)', 'male|female', imageWidth).toBuffer(function (err,buffer){
    //Do something with buffer. eg buffer.toString('base64');
});
```
i've updated readme with usage examples.
